# Generated by Django 3.0.2 on 2020-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='id',
        ),
        migrations.AlterField(
            model_name='folder',
            name='dir',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
